### ISSUE TITLE
RFC: X-Real-Ip Header not trustable, X-Forwarded-For more reliable 

### ISSUE THREAD

**Issue by vherrlein** [fbonalair/traefik-crowdsec-bouncer#17]
https://github.com/fbonalair/traefik-crowdsec-bouncer/blob/403c736ae499c6dc2c193f87dd37d8810033f100/controler/controler.go#L116

Dear,

In case of an architecture with proxy-chaining _(TCP, HTTP, SNAT...)_, the X-Real-Ip header is not trustable on Traefik.
It would be great to implement an option allowing the usage of the X-Forwarded-For instead of X-Real-Ip.

Its format:
> X-Forwarded-For: < Client IP >, < Proxy IP 1 >, < Proxy IP 2 >

Examples of values:

> X-Forwarded-For: 192.168.10.11
> X-Forwarded-For: 123.123.123.123, 172.16.1.1
> X-Forwarded-For: 123.123.123.123, 172.16.1.1, 10.50.1.1
> X-Forwarded-For: 123.123.123.123, 172.16.1.1, 10.50.1.1, 1.1.1.1

So, when XFF is used, only the first IP is relevant.

Thank you in advance.

**Comment by fbonalair** [comment]
Thank you for details. The fix have been done for issue #10. Feel free to leave your comment there.
