### ISSUE TITLE
Docker image for linux/arm/v7

### ISSUE THREAD

**Issue by niveksan** [fbonalair/traefik-crowdsec-bouncer#19]
Would you mind building and pushing linux/arm/v7 image to dockerhub?

**Comment by fbonalair** [comment]
I've just update the pipeline, a linux/arm/v7 container is available on dockerhub from version 0.3.5 and on.   
I haven't tested it though, can you?

**Comment by niveksan** [comment]
Seems to be working fine. Thank you very much.

**Comment by fbonalair** [comment]
You are welcome
