### ISSUE TITLE
Can this bouncer be used for other non-http services (i.e. tcp/udp)?

### ISSUE THREAD

**Issue by jagbarcelo** [fbonalair/traefik-crowdsec-bouncer#23]
All examples and documentation lead towards the most obvious usage, which is http/https trafic being directed to this middleware in order to sort out if the request is granted/denied later down the pipe.

However, my question is targeted to other services with plain tcp connections (even udp): Can this middleware be used in those cases too. Could it be used, for instance, to protect incoming connections to 25565 port (minecraft) from bad actors?

If so, how? Some examples would be great. Thanks.

**Comment by fbonalair** [comment]
Unfortunately this bouncer service Traefik [ForwardAuth](https://doc.traefik.io/traefik/middlewares/http/forwardauth/) middleware only supported for HTTP. And for TCP, neither [InFlightConn](https://doc.traefik.io/traefik/middlewares/tcp/inflightconn/) nor [IPWhiteList](https://doc.traefik.io/traefik/middlewares/tcp/ipwhitelist/) would be suitable for with this bouncer.

Maybe you can ask guys at Traefik for a new middleware for this use case?
