### ISSUE TITLE
Configurable response codes?

### ISSUE THREAD

**Issue by RoboMagus** [fbonalair/traefik-crowdsec-bouncer#26]
I'd like the option to have configurable response codes i.s.o. the standard `403`.

Yes, this is technically not quite right, but based on these return codes attackers could steer their search.
Between `404`: Nothing here, vs `403`: something here but no right to access, I'd like to have any malicious query think there's no benefit in attempting a retry.

Adding an environment variable (e.g. `BAN_RESPONSE_CODE`) to configure what response code should be used would enable this.

**Comment by fbonalair** [comment]
I was thinking of a feature like this while developing, but wasn't a priority.   
It should be simple to implement, I will look into it.
