### ISSUE TITLE
capi cant load 

### ISSUE THREAD

**Issue by geekblog-dev** [fbonalair/traefik-crowdsec-bouncer#27]
Hello there just installed with a little guide:
https://docs.technotim.live/posts/crowdsec-traefik/

And had the same issue as described here:
https://github.com/crowdsecurity/crowdsec/issues/1324

```
$ sudo cscli capi register
WARN[08-03-2022 04:55:27 PM] can't load CAPI credentials from '/etc/crowdsec/online_api_credentials.yaml' (missing field) 
INFO[08-03-2022 04:55:27 PM] push and pull to Central API disabled        
FATA[08-03-2022 04:55:28 PM] api client register ('https://api.crowdsec.net/'): api register (https://api.crowdsec.net/) http 400 Bad Request : http code 400, invalid body: invalid character '\'' in string escape code: http code 400, invalid body: invalid character '\'' in string escape code

```
So i am new to crowdsec but without capi detection is not possible, as i understand so this should be addressed.

Hope this helps.

**Comment by fbonalair** [comment]
This is a Crowdsec issue not linked to the bouncer, and from your link Crowdsec teams are already handling it.
