### ISSUE TITLE
Bouncing Traefik TCP connections?

### ISSUE THREAD

**Issue by comminutus** [fbonalair/traefik-crowdsec-bouncer#34]
I have a few services that are exposed in Traefik via TCP entrypoints.  I'd like to bounce TCP connections that CrowdSec identifies as threats.  Does this bouncer only handle HTTP-based connections?

**Comment by fbonalair** [comment]
Last time I've checked, Traefik expose the Auth Middleware only for HTTP request. So this bouncer only work with HTTP connection.
