### ISSUE TITLE
UnmarshalJSON : invalid character parsing issue

### ISSUE THREAD

**Issue by gabeclarke** [fbonalair/traefik-crowdsec-bouncer#52]
Hi,

This is just a snippet of my crowdsec logs, it appears that traefik-crowdsec-bouncer is working as expected but I continue to see this UnmarshalJSON parsing error with a high frequency. Is this expected or a misconfiguration on my end?

There are no errors showing in the traefik-crowdsec-bouncer logs or I would post those as well. 

Please let me know what other details you need from me, thanks!

time="03-08-2023 10:36:46" level=warning msg="failed to run filter : invalid character 'i' in literal true (expecting 'r') (1:1)\n | UnmarshalJSON(evt.Line.Raw, evt.Unmarshaled, \"traefik\") in [\"\", nil]\n | ^" id=lingering-darkness name=child-crowdsecurity/traefik-logs stage=s01-parse
08/03/2023 10:36:46 AM
time="03-08-2023 10:36:46" level=info msg=" - [Thu, 03 Aug 2023 10:36:46 MDT] \"GET /v1/decisions?type=ban&ip={iphere} HTTP/1.1 200 21.219981ms \"Go-http-client/1.1\" \""
08/03/2023 10:36:47 AM
time="03-08-2023 10:36:47" level=info msg="{iphere} - [Thu, 03 Aug 2023 10:36:47 MDT] \"GET /v1/decisions?type=ban&ip={iphere} HTTP/1.1 200 6.881124ms \"Go-http-client/1.1\" \""
08/03/2023 10:36:47 AM
time="03-08-2023 10:36:47" level=info msg="{iphere} - [Thu, 03 Aug 2023 10:36:47 MDT] \"GET /v1/decisions?type=ban&ip={iphere} HTTP/1.1 200 6.447098ms \"Go-http-client/1.1\" \""
08/03/2023 10:37:06 AM
time="03-08-2023 10:37:06" level=info msg="{iphere} - [Thu, 03 Aug 2023 10:37:06 MDT] \"GET /v1/heartbeat HTTP/1.1 200 1.77173ms \"crowdsec/v1.5.2-4fbc3402fba932c8bd34b671527dcf7909d264c0\" \""
08/03/2023 10:37:24 AM
time="03-08-2023 10:37:24" level=info msg="{iphere} - [Thu, 03 Aug 2023 10:37:24 MDT] \"GET /v1/decisions?type=ban&ip={iphere} HTTP/1.1 200 23.497711ms \"Go-http-client/1.1\" \""
08/03/2023 10:37:47 AM
time="03-08-2023 10:37:47" level=info msg="{iphere} - [Thu, 03 Aug 2023 10:37:47 MDT] \"GET /v1/decisions?type=ban&ip={iphere} HTTP/1.1 200 25.33208ms \"Go-http-client/1.1\" \""
08/03/2023 10:37:47 AM
time="03-08-2023 10:37:47" level=info msg="{iphere} - [Thu, 03 Aug 2023 10:37:47 MDT] \"GET /v1/decisions?type=ban&ip={iphere} HTTP/1.1 200 6.217236ms \"Go-http-client/1.1\" \""
08/03/2023 10:37:47 AM
time="03-08-2023 10:37:47" level=error msg="UnmarshalJSON : invalid character 'i' in literal true (expecting 'r')"
08/03/2023 10:37:47 AM
time="03-08-2023 10:37:47" level=warning msg="failed to run filter : invalid character 'i' in literal true (expecting 'r') (1:1)\n | UnmarshalJSON(evt.Line.Raw, evt.Unmarshaled, \"traefik\") in [\"\", nil]\n | ^" id=lingering-darkness name=child-crowdsecurity/traefik-logs stage=s01-parse
08/03/2023 10:37:47 AM
time="03-08-2023 10:37:47" level=info msg="{iphere} - [Thu, 03 Aug 2023 10:37:47 MDT] \"GET /v1/decisions?type=ban&ip={iphere} HTTP/1.1 200 6.273219ms \"Go-http-client/1.1\" \""

**Comment by macvenez** [comment]
I had the same error, you have to remove the traefik log and just leave the accessLog.
For what I understood crowdsec is not configured to read traefik logs (and only auth logs) maybe?

**Comment by gabeclarke** [comment]
Thank you dude! That was the problem, after removing the traefik log from acquis.yml the error messages go away. So I believe in this case, it had nothing to do with the bouncer.

**Comment by macvenez** [comment]
> Thank you dude! That was the problem, after removing the traefik log from acquis.yml the error messages go away. So I believe in this case, it had nothing to do with the bouncer.

No worries! I don't know why they tell to include it in some guides... maybe they don't even test their setups afterwards?

**Comment by miiraheart** [comment]
I am having this same issue as well

**Comment by macvenez** [comment]
> I am having this same issue as well

Hi, if you have a similar setup as mine was, probably you'll have to remove the traefik standard log from crowdsec config file and just leave the access log
